// Package db2dialect provides Bun ORM support for IBM DB2
package db2dialect

import (
	"github.com/uptrace/bun/schema"
)

// AppendSequence appends the DB2 sequence/identity clause for auto-increment fields
// DB2 uses GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)
func (d *Dialect) AppendSequence(b []byte, table *schema.Table, field *schema.Field) []byte {
	// Only append sequence for primary key integer fields
	if !field.IsPK || field.CreateTableSQLType != "BIGINT" && field.CreateTableSQLType != "INTEGER" {
		return b
	}

	// Append DB2 identity clause
	b = append(b, " GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)"...)
	return b
}

// AppendOffsetLimit generates DB2 OFFSET...FETCH NEXT SQL syntax
// Used for pagination: OFFSET n ROWS FETCH NEXT m ROWS ONLY
func AppendOffsetLimit(b []byte, offset, limit int64) []byte {
	if offset > 0 {
		b = append(b, " OFFSET "...)
		b = appendInt(b, offset)
		b = append(b, " ROWS"...)
	}

	if limit > 0 {
		b = append(b, " FETCH NEXT "...)
		b = appendInt(b, limit)
		b = append(b, " ROWS ONLY"...)
	}

	return b
}

// appendInt is a helper to append an int64 as ASCII digits
func appendInt(b []byte, num int64) []byte {
	if num == 0 {
		return append(b, '0')
	}

	if num < 0 {
		b = append(b, '-')
		num = -num
	}

	// Convert number to string by repeatedly dividing by 10
	var digits [20]byte
	i := len(digits)
	for num > 0 {
		i--
		digits[i] = byte((num % 10) + '0')
		num /= 10
	}

	return append(b, digits[i:]...)
}
