package main

import (
	"strings"
	"testing"
	"time"

	"github.com/ibmdb/go_ibm_db/db2dialect"
	"github.com/uptrace/bun"
)

type CrossPlatformItem struct {
	ID        int64                   `bun:",pk,autoincrement"`
	Title     string                  `bun:",notnull"`
	Amount    float64                 `bun:""`
	Active    db2dialect.SmallIntBool `bun:""`
	CreatedAt time.Time               `bun:",default:current_timestamp"`
}

func TestBunCrossPlatform_CreateTable(t *testing.T) {
	targets := []struct {
		target        db2dialect.TargetPlatform
		name          string
		wantDefClause string
	}{
		{db2dialect.TargetLUW, "LUW", "DEFAULT current_timestamp"},
		{db2dialect.TargetZOS, "z/OS", "TIMESTAMP, PRIMARY KEY"},
		{db2dialect.TargetIBMi, "IBM i", "DEFAULT current_timestamp"},
	}

	for _, tc := range targets {
		t.Run(tc.name, func(t *testing.T) {
			dialect := db2dialect.New(db2dialect.WithTarget(tc.target))
			db := bun.NewDB(nil, dialect)

			q := db.NewCreateTable().Model((*CrossPlatformItem)(nil)).IfNotExists()
			sql := q.String()

			t.Logf("[%s] CreateTable SQL: %s", tc.name, sql)

			if !strings.Contains(sql, `GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)`) {
				t.Errorf("[%s] Expected GENERATED BY DEFAULT AS IDENTITY clause, got: %s", tc.name, sql)
			}

			if !strings.Contains(sql, tc.wantDefClause) {
				t.Errorf("[%s] Expected default clause %q, got: %s", tc.name, tc.wantDefClause, sql)
			}
		})
	}
}

func TestBunCrossPlatform_Pagination(t *testing.T) {
	targets := []struct {
		target db2dialect.TargetPlatform
		name   string
	}{
		{db2dialect.TargetLUW, "LUW"},
		{db2dialect.TargetZOS, "z/OS"},
		{db2dialect.TargetIBMi, "IBM i"},
	}

	for _, tc := range targets {
		t.Run(tc.name, func(t *testing.T) {
			dialect := db2dialect.New(db2dialect.WithTarget(tc.target))
			db := bun.NewDB(nil, dialect)

			var items []CrossPlatformItem
			q := db.NewSelect().Model(&items).Order("id ASC").Offset(10).Limit(5)
			sql := q.String()

			t.Logf("[%s] Select Pagination SQL: %s", tc.name, sql)

			expected := "OFFSET 10 ROWS FETCH NEXT 5 ROWS ONLY"
			if !strings.Contains(sql, expected) {
				t.Errorf("[%s] Expected pagination clause %q, got: %s", tc.name, expected, sql)
			}
		})
	}
}

func TestBunCrossPlatform_DMLStatements(t *testing.T) {
	targets := []struct {
		target db2dialect.TargetPlatform
		name   string
	}{
		{db2dialect.TargetLUW, "LUW"},
		{db2dialect.TargetZOS, "z/OS"},
		{db2dialect.TargetIBMi, "IBM i"},
	}

	for _, tc := range targets {
		t.Run(tc.name, func(t *testing.T) {
			dialect := db2dialect.New(db2dialect.WithTarget(tc.target))
			db := bun.NewDB(nil, dialect)

			item := &CrossPlatformItem{Title: "Widget", Amount: 99.95, Active: db2dialect.SmallIntBool(1)}

			// Insert
			insertSQL := db.NewInsert().Model(item).String()
			t.Logf("[%s] Insert SQL: %s", tc.name, insertSQL)
			if !strings.Contains(insertSQL, `INSERT INTO "cross_platform_items"`) {
				t.Errorf("[%s] Invalid Insert SQL: %s", tc.name, insertSQL)
			}

			// Update
			updateSQL := db.NewUpdate().Model(item).Where("id = ?", 1).String()
			t.Logf("[%s] Update SQL: %s", tc.name, updateSQL)
			if !strings.Contains(updateSQL, `UPDATE "cross_platform_items"`) {
				t.Errorf("[%s] Invalid Update SQL: %s", tc.name, updateSQL)
			}

			// Delete
			deleteSQL := db.NewDelete().Model((*CrossPlatformItem)(nil)).Where("id = ?", 1).String()
			t.Logf("[%s] Delete SQL: %s", tc.name, deleteSQL)
			if !strings.Contains(deleteSQL, `DELETE FROM "cross_platform_items"`) {
				t.Errorf("[%s] Invalid Delete SQL: %s", tc.name, deleteSQL)
			}
		})
	}
}
